### PR TITLE
ws noughts crosses fix

### PR DESCRIPTION
**Pull request by hansvb**
- noughtscrosses: improve tests
- fix gorilla dependency

### CODE REVIEW

**Comment by hansvb** [comment]
I didn't refactor `TestMessageTypeUnmarshalJSON` yet in the same style. You can do that first if you want by adding to this RP before merging? @adoublef

**Comment by hansvb** [comment]
I'm using table-driven tests: https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

**Comment by hansvb** [comment]
And also it seemed cleaner to me to put the double quotes inside backtick-quoted strings in stead of escaping the double quotes.

**Review by adoublef — APPROVED** [review]
`message_test.go` passed tests with 64% coverage

**Pull request merged**
